@apiendpoint = http://localhost:5001

### CHECK METHODS ALLOWED
OPTIONS {{apiendpoint}}/api/web/incoming HTTP/1.1
Access-Control-Request-Method: POST
Origin: http://localhost:4200

### WEB CONTROLLER FOR COMMANDS
POST {{apiendpoint}}/api/web/incoming HTTP/1.1
Content-Type: application/json

{
    "message": "corporate"
}
### WEB CONTROLLER FOR COMMANDS
POST {{apiendpoint}}/api/web/incoming HTTP/1.1
Content-Type: application/json

{
    "message": "dota"
}

### WEB CONTROLLER FOR COMMANDS
POST {{apiendpoint}}/api/web/incoming HTTP/1.1
Content-Type: application/json

{
    "message": "promatches"
}

### WEB CONTROLLER FOR COMMANDS
POST {{apiendpoint}}/api/web/incoming HTTP/1.1
Content-Type: application/json

{
    "message": "api"
}

### WEB CONTROLLER FOR COMMANDS
POST {{apiendpoint}}/api/web/incoming HTTP/1.1
Content-Type: application/json

{
    "message": "DOG"
}

### WEB CONTROLLER FOR COMMANDS
POST {{apiendpoint}}/api/web/incoming HTTP/1.1
Content-Type: application/json

{
    "message": "nonexisting"
}

### CORPORATE BULL SHIT
GET https://corporatebs-generator.sameerkumar.website/ HTTP/1.1

### GOOGLE STATIC MAPS API
GET https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=12&size=400x400&key={{GoogleStaticMapsAPIKey}} HTTP/1.1

### Get Players Info ###
GET https://api.opendota.com/api/players/76561198050295075 HTTP/1.1

### Gets Pro Matches Info ###
GET https://api.opendota.com/api/proMatches HTTP/1.1

### Gets Pro Match Info ###
GET https://api.opendota.com/api/matches/5169398792 HTTP/1.1


### Gets Pro Matches Info ###
GET https://dog.ceo/api/breeds/image/random HTTP/1.1
