@apiendpoint = https://c5cced1a.ngrok.io/api
@whatsappcontrollerUrl = http://localhost:5000/api/whatsapp
@telegramWebHookUrl =  {{apiendpoint}}/telegram/incoming

###Send a message on whats app
POST {{whatsappcontrollerUrl}}  HTTP/1.1
Content-Type: application/json

{
    "body":"Yo Yo",
    "tophonenumber":"whatsapp:+919916242328"
}

###Receive a message from whats app
POST {{whatsappcontrollerUrl}}/incoming HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ApiVersion=2010-04-01&SmsSid=abcd&SmsStatus=received&SmsMessageSid=abcd&NumSegments=1&From=whatsapp%3A%2B919916242328&To=whatsapp%3A%2B14155238886&MessageSid=abcd&Body=cc/%20abcde&AccountSid=abcd&NumMedia=0

### CORPORATE BULL SHIT
GET https://corporatebs-generator.sameerkumar.website/ HTTP/1.1


### GOOGLE STATIC MAPS API
GET https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=12&size=400x400&key={{GoogleStaticMapsAPIKey}} HTTP/1.1


### TELEGRAM API ######

### Get Updates ###
GET https://api.telegram.org/bot{{TelegramGuideMeInBangaloreAPIKKey}}/getUpdates HTTP/1.1

### SetWebHook ###
GET https://api.telegram.org/bot{{TelegramGuideMeInBangaloreAPIKKey}}/setWebhook?url={{telegramWebHookUrl}} HTTP/1.1

### GetWebHook Information ###
GET https://api.telegram.org/bot{{TelegramGuideMeInBangaloreAPIKKey}}/getWebhookInfo HTTP/1.1


### Send Message ###
GET https://api.telegram.org/bot{{TelegramGuideMeInBangaloreAPIKKey}}/sendMessage?chat_id=666535987&text=testtesttest HTTP/1.1


### Post Message to Webhook###
POST {{telegramWebHookUrl}} HTTP/1.1
Content-Type: application/json

{
    "body":"Yo Yo",
    "tophonenumber":"whatsapp:+919916242328"
}